name: test_case
description: "A new Flutter project."
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  # animated_bottom_navigation_bar: ^1.3.0
  auto_route: ^10.0.0
  carousel_slider: ^5.0.0
  collection: ^1.19.1
  cross_connectivity: ^3.3.0
  cupertino_icons: ^1.0.8
  currency_text_input_formatter: ^2.2.8 
  device_info_plus: ^11.3.3
  dio: ^5.8.0+1
  # dropdown_button2: ^2.3.9
  easy_localization: ^3.0.7+1  
  email_validator: ^3.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  # flutter_map: ^7.0.2
  # flutter_map_animations: ^0.9.0
  # flutter_map_geojson: ^1.0.7
  flutter_native_image: ^0.0.6+1
  flutter_native_splash: ^2.4.5

  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  flutter_svg_provider: ^1.0.7
  fluttertoast: ^8.2.12
  fpdart: ^1.1.1
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  hooks_riverpod: ^2.6.1
  http_parser: ^4.1.2
  injectable: ^2.5.0
  intl: 0.19.0
  inner_shadow_widget: ^0.0.3
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1

  lottie: ^3.3.1
  mask_text_input_formatter: ^2.9.0
  mime: ^2.0.0
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
 
  shared_preferences: ^2.5.2

dev_dependencies:
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  change_app_package_name: ^1.5.0
  flutter_gen_runner: ^5.10.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.3
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.4
  lint: ^2.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/
    - assets/lottie/

  fonts:
    - family: Euclid Circular A
      fonts:
        - asset: assets/fonts/Euclid Circular A Light.ttf
          weight: 300
        - asset: assets/fonts/Euclid Circular A Light Italic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Euclid Circular A Regular.ttf
          weight: 400
        - asset: assets/fonts/Euclid Circular A Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Euclid Circular A Medium.ttf
          weight: 500
        - asset: assets/fonts/Euclid Circular A SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Euclid Circular A SemiBold Italic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Euclid Circular A Bold.ttf
          weight: 700
        - asset: assets/fonts/Euclid Circular A Bold Italic.ttf
          weight: 700
          style: italic






          

flutter_gen:
  assets:
    enabled: true
  integrations:
    flutter_svg: true